# backend/courselinksgenerate.py
import json
import re

BASE = "https://bulletins.psu.edu/university-course-descriptions/undergraduate/"

# 📋 Paste your department list here
raw_text = """
Accounting (ACCTG)
Acoustics (ACS)
Adult Education (ADTED)
Aerospace Engineering (AERSP)
African American Studies (AFAM)
African Studies (AFR)
Agribusiness Management (AGBM)
Agricultural and Biorenewable Systems Management (ABSM)
Agricultural and Extension Education (AEE)
Agricultural Communications (AGCOM)
Agricultural Science (AGSC)
Agricultural Systems Management (ASM)
Agriculture (AG)
Agroecology (AGECO)
Agronomy (AGRO)
Air Force (AIR)
American Studies (AMST)
Animal Science (ANSC)
Anthropology (ANTH)
Applied Behavior Analysis (ABA)
Applied Linguistics (APLNG)
Applied Youth, Family and Community Education (AYFCE)
Arabic (ARAB)
Architectural Engineering (AE)
Architectural Engineering Technology (AET)
Architecture (ARCH)
Army (ARMY)
Art (ART)
Art Education (AED)
Art History (ARTH)
Artificial Intelligence (A-I)
Artificial Intelligence Engineering (AIE)
Artificial Intelligence Methods and Applications (AIMA)
Arts Administration (ARTSA)
Arts and Architecture (AA)
Asian American Studies (AAS)
Asian Studies (ASIA)
Astronomy and Astrophysics (ASTRO)
Athletic Training (ATHTR)
Behavioral Sciences - CA (BESC)
Biobehavioral Health (BBH)
Biochemistry and Molecular Biology (BMB)
Bioethics (BIOET)
Bioethics and Medical Humanities (BMH)
Biological Engineering (BE)
Biological Science (BISC)
Biology (BIOL)
Biomedical Engineering (BME)
Biomedical Engineering Technology (BE_T)
Biorenewable Systems (BRS)
Biotechnology (BIOTC)
Business Administration (BA)
Business Law (BLAW)
Chemical Engineering (CHE)
Chemistry (CHEM)
Chinese (CHNS)
Civil Engineering (CE)
Communication Arts and Sciences (CAS)
Communication Sciences and Disorders (CSD)
Communications (COMM)
Computer Science (CMPSC)
Criminology (CRIM)
Cybersecurity Analytics and Operations (CYBER)
Data Sciences (DS)
Economics (ECON)
Electrical Engineering (EE)
English (ENGL)
Enterprise Technology Integration (ETI)
Finance (FIN)
Food Science (FDSC)
French (FR)
Geography (GEOG)
Geosciences (GEOSC)
German (GER)
Health Policy and Administration (HPA)
History (HIST)
Human Development and Family Studies (HDFS)
Human-Centered Design and Development (HCDD)
Industrial Engineering (IE)
Information Sciences and Technology (IST)
Kinesiology (KINES)
Management (MGMT)
Management Information Systems (MIS)
Marketing (MKTG)
Mathematics (MATH)
Mechanical Engineering (ME)
Meteorology (METEO)
Microbiology (MICRB)
Music (MUSIC)
Nursing (NURS)
Nutrition (NUTR)
Philosophy (PHIL)
Physics (PHYS)
Political Science (PLSC)
Psychology (PSYCH)
Sociology (SOC)
Spanish (SPAN)
Statistics (STAT)
Supply Chain Management (SCM)
Theatre (THEA)
Women's Gender and Sexuality Studies (WGSS)
"""

# --- Parse names and abbreviations ---
pattern = re.compile(r"^(.*?)\s*\(([-A-Z0-9_]+)\)", re.MULTILINE)
departments = []

for match in pattern.finditer(raw_text):
    name = match.group(1).strip()
    code = match.group(2).strip().lower()
    link = f"{BASE}{code}/"
    departments.append({
        "name": f"{name} ({code.upper()})",
        "link": link
    })

print(f"✅ Generated {len(departments)} department links.")

# --- Save as courselinks.json ---
with open("courselinks.json", "w") as f:
    json.dump(departments, f, indent=2)

print("💾 Saved courselinks.json successfully.")
